### ISSUE TITLE
[main] Flaky on ovs-cni lane

### ISSUE THREAD

**Issue by RamLavi** [kubevirt/cluster-network-addons-operator#1388]
**What happened**:
failing jobs: [[0]](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1387/pull-e2e-cluster-network-addons-operator-ovs-cni-functests/1541401451966763008), [[1]](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1380/pull-e2e-cluster-network-addons-operator-ovs-cni-functests/1540967541420068864) 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by RamLavi** [comment]
error: 
```
ovs-cni 0.3.1 pod ovs-bridge connectivity tests when an OVS bridge is configured on a node and a network attachment definition is defined and two pods are connected through it 
  they should be able to communicate over the network
  /tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/tests/ovs_test.go:79
STEP: Adding ovs-bridge on the node
./cluster/ssh.sh node01 -- sudo ovs-vsctl add-br br-test
stdout: ...
, stderr selecting docker as container runtime
STEP: Adding NetworkAttachmentDefinition ovs-net of ovs bridge
STEP: Creating pod pod-test-1 with priviliged premission and ip 10.0.0.1/24
STEP: Waiting for pod container to be in Running state
panic: test timed out after 10m0s
goroutine 236 [running]:
testing.(*M).startAlarm.func1()
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/testing/testing.go:1788 +0x8e
created by time.goFunc
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/time/sleep.go:180 +0x31
goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc000602340, {0x12b01be, 0x46d473}, 0x13551e0)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/testing/testing.go:1307 +0x375
testing.runTests.func1(0xc00033adb0)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/testing/testing.go:1598 +0x6e
testing.tRunner(0xc000602340, 0xc0002d1d18)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/testing/testing.go:1259 +0x102
testing.runTests(0xc00027c200, {0x1e4c400, 0x1, 0x1}, {0x48bc4d, 0x12b53ca, 0x1e7d9e0})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/testing/testing.go:1596 +0x43f
testing.(*M).Run(0xc00027c200)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/testing/testing.go:1504 +0x51d
main.main()
	_testmain.go:43 +0x14b
goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/k8s.io/klog/v2/klog.go:1169 +0x6a
created by k8s.io/klog/v2.init.0
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/k8s.io/klog/v2/klog.go:417 +0xfb
goroutine 116 [select]:
github.com/onsi/gomega/internal.(*AsyncAssertion).match(0xc000304c80, {0x1455130, 0x1eaeca0}, 0x1, {0xc00098acf0, 0x1, 0x1})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/gomega/internal/async_assertion.go:183 +0x4db
github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0xc000304c80, {0x1455130, 0x1eaeca0}, {0xc00098acf0, 0x1, 0x1})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/gomega/internal/async_assertion.go:92 +0x6b
github.com/k8snetworkplumbingwg/ovs-cni/tests/cluster.(*ClusterAPI).CreatePrivilegedPodWithIP(0xc00053b8a8, {0x12b08b2, 0xa}, {0x12ace1b, 0x7}, {0x12ac5f5, 0x7}, {0x12b0dfe, 0xb})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/tests/cluster/cluster.go:130 +0x6f1
github.com/k8snetworkplumbingwg/ovs-cni/tests_test.glob..func5.2.1.3.3.1()
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/tests/ovs_test.go:72 +0x53
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0x0)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0xba
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0x0)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0x125
github.com/onsi/ginkgo/internal/leafnodes.(*SetupNode).Run(0xc000602680)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/internal/leafnodes/setup_nodes.go:15 +0x7b
github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc0001b2690, 0xc00059d9f0, {0x143fe60, 0xc0002668c0})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:193 +0x5ec
github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc0001b2690, {0x143fe60, 0xc0002668c0})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0xe7
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc000536000, 0xc0001b2690)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0xe5
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc000536000)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x1a5
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc000536000)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:66 +0xc5
github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0002809a0, {0x7f4e7d899f38, 0xc0006024e0}, {0x12b2508, 0x1}, {0xc0003275c0, 0x2, 0x2}, {0x1477d58, 0xc0002668c0}, ...)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:79 +0x4d2
github.com/onsi/ginkgo.runSpecsWithCustomReporters({0x1440e40, 0xc0006024e0}, {0x12b2508, 0xc}, {0xc0003275a0, 0x2, 0x12c0a45})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:238 +0x185
github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters({0x1440e40, 0xc0006024e0}, {0x12b2508, 0xc}, {0xc000546ed0, 0x1, 0x1})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:221 +0x1be
github.com/k8snetworkplumbingwg/ovs-cni/tests_test.TestPlugin(0x0)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/tests/tests_suite_test.go:39 +0x165
testing.tRunner(0xc0006024e0, 0x13551e0)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/testing/testing.go:1306 +0x35a
goroutine 60 [chan receive, 9 minutes]:
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).registerForInterrupts(0xc000536000, 0x13551e0)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:223 +0x9d
created by github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:60 +0x9d
goroutine 62 [syscall, 9 minutes]:
os/signal.signal_recv()
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/os/signal/signal.go:151 +0x2c
goroutine 65 [IO wait]:
internal/poll.runtime_pollWait(0x7f4e6ffebed8, 0x72)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc0007b0d80, 0xc00061c000, 0x0)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0007b0d80, {0xc00061c000, 0x6e08, 0x6e08})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0007b0d80, {0xc00061c000, 0xc00061c005, 0x9c4})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc0000100c0, {0xc00061c000, 0x6, 0xc0001c37f0})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000484e10, {0xc00061c000, 0x0, 0x40bcad})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc0002e9778, {0x143f120, 0xc000484e10})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0002e9500, {0x14409a0, 0xc0000100c0}, 0x6e08)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0002e9500, 0x0)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc0002e9500, {0xc0001f1000, 0x1000, 0x43a320})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc000153aa0, {0xc0001e2120, 0x9, 0x0})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x143ef80, 0xc000153aa0}, {0xc0001e2120, 0x9, 0x9}, 0x9)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/build/_output/bin/go/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader({0xc0001e2120, 0x9, 0xc00039fc50}, {0x143ef80, 0xc000153aa0})
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/golang.org/x/net/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001e20e0)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/golang.org/x/net/http2/frame.go:498 +0x95
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0001c3f98)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/golang.org/x/net/http2/transport.go:2052 +0x130
golang.org/x/net/http2.(*ClientConn).readLoop(0xc0002e0d80)
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/golang.org/x/net/http2/transport.go:1948 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/tmp/deploy.ovs-cni.KZmZ/github.com/k8snetworkplumbingwg/ovs-cni/vendor/golang.org/x/net/http2/transport.go:701 +0xac5
FAIL	github.com/k8snetworkplumbingwg/ovs-cni/tests	600.017s
```
